import type { CatalogItem, Category, ItemId, UpgradeDef } from "./types";

export const CATALOG: CatalogItem[] = [
  {
    id: "tbar",
    category: "lifts",
    name: "Schlepplift",
    blurb: "Günstig, für Anfängerhänge. Bis 800 Pers./h.",
    cost: 4500,
    xp: 18,
    unlockLevel: 1,
    buildSeconds: 6,
    footprint: 1,
    maxSlope: 0.55,
    minElev: 1600,
    maxElev: 2800,
    capacity: 800,
    speed: 3.2,
    minSpan: 4,
    maxSpan: 14,
    color: "#3d6ea8",
  },
  {
    id: "chair",
    category: "lifts",
    name: "Sessellift",
    blurb: "Komfortabler 4er-Sessel. Bis 1.800 Pers./h.",
    cost: 18500,
    xp: 36,
    unlockLevel: 2,
    buildSeconds: 10,
    footprint: 1,
    maxSlope: 0.7,
    minElev: 1600,
    maxElev: 3400,
    capacity: 1800,
    speed: 4.2,
    minSpan: 6,
    maxSpan: 20,
    color: "#1a73e8",
  },
  {
    id: "gondola",
    category: "lifts",
    name: "Gondelbahn",
    blurb: "Befördert bis zu 2.400 Personen pro Stunde.",
    cost: 45000,
    xp: 70,
    unlockLevel: 3,
    buildSeconds: 14,
    footprint: 1,
    maxSlope: 1.1,
    minElev: 1600,
    maxElev: 3900,
    capacity: 2400,
    speed: 6,
    minSpan: 8,
    maxSpan: 28,
    color: "#1557b0",
  },
  {
    id: "tram",
    category: "lifts",
    name: "Pendelbahn",
    blurb: "Steile Wände, grosse Kabinen. 900 Pers./h.",
    cost: 82000,
    gemCost: 40,
    xp: 110,
    unlockLevel: 6,
    buildSeconds: 18,
    footprint: 1,
    maxSlope: 1.6,
    minElev: 1700,
    maxElev: 4500,
    capacity: 900,
    speed: 8,
    minSpan: 10,
    maxSpan: 32,
    color: "#0b1f3a",
  },
  {
    id: "restaurant",
    category: "buildings",
    name: "Restaurant",
    blurb: "Sonnenterrasse. Skifahrer geben hier Geld aus.",
    cost: 12000,
    xp: 24,
    unlockLevel: 1,
    buildSeconds: 8,
    footprint: 1,
    maxSlope: 0.32,
    minElev: 1600,
    maxElev: 3200,
    color: "#8b4a2b",
  },
  {
    id: "hut",
    category: "buildings",
    name: "Berghütte",
    blurb: "Klassische Walliser Hütte mit Glühwein.",
    cost: 8000,
    xp: 16,
    unlockLevel: 2,
    buildSeconds: 7,
    footprint: 1,
    maxSlope: 0.4,
    minElev: 1800,
    maxElev: 3400,
    color: "#6b3f24",
  },
  {
    id: "hotel1",
    category: "buildings",
    name: "Hotel ★",
    blurb: "60 Betten. Gäste bleiben über Nacht.",
    cost: 28000,
    xp: 40,
    unlockLevel: 3,
    buildSeconds: 14,
    footprint: 1,
    maxSlope: 0.22,
    minElev: 1580,
    maxElev: 2100,
    beds: 60,
    color: "#9a6a45",
  },
  {
    id: "hotel3",
    category: "buildings",
    name: "Hotel ★★★",
    blurb: "140 Betten, Halbpension, höhere Raten.",
    cost: 64000,
    xp: 80,
    unlockLevel: 5,
    buildSeconds: 18,
    footprint: 1,
    maxSlope: 0.2,
    minElev: 1580,
    maxElev: 2050,
    beds: 140,
    color: "#7a4a32",
  },
  {
    id: "hotel5",
    category: "buildings",
    name: "Palace ★★★★★",
    blurb: "240 Betten. Luxus, Spa, enorme Einnahmen.",
    cost: 140000,
    gemCost: 80,
    xp: 150,
    unlockLevel: 8,
    buildSeconds: 24,
    footprint: 1,
    maxSlope: 0.18,
    minElev: 1580,
    maxElev: 2000,
    beds: 240,
    color: "#3d2a22",
  },
  {
    id: "shop",
    category: "buildings",
    name: "Sportshop",
    blurb: "Ski, Helm, Souvenirs. Bonus auf Zufriedenheit.",
    cost: 9500,
    xp: 18,
    unlockLevel: 2,
    buildSeconds: 7,
    footprint: 1,
    maxSlope: 0.28,
    minElev: 1580,
    maxElev: 2400,
    color: "#2f6f8f",
  },
  {
    id: "skischool",
    category: "buildings",
    name: "Skischule",
    blurb: "Mehr Anfänger, höhere Auslastung blauer Pisten.",
    cost: 16000,
    xp: 28,
    unlockLevel: 4,
    buildSeconds: 10,
    footprint: 1,
    maxSlope: 0.3,
    minElev: 1580,
    maxElev: 2300,
    color: "#c45c2a",
  },
  {
    id: "ticket",
    category: "buildings",
    name: "Kasse",
    blurb: "Talstation-Tickets. +8 % Einnahmen im Umkreis.",
    cost: 6000,
    xp: 12,
    unlockLevel: 1,
    buildSeconds: 5,
    footprint: 1,
    maxSlope: 0.25,
    minElev: 1580,
    maxElev: 2000,
    color: "#1a73e8",
  },
  {
    id: "apres",
    category: "buildings",
    name: "Après-Ski",
    blurb: "Hütte mit Musik. Abends extra Umsatz.",
    cost: 18000,
    xp: 30,
    unlockLevel: 4,
    buildSeconds: 9,
    footprint: 1,
    maxSlope: 0.28,
    minElev: 1580,
    maxElev: 2400,
    color: "#b03a3a",
  },
  {
    id: "spa",
    category: "buildings",
    name: "Berg-Spa",
    blurb: "Wellness nach der Abfahrt. Luxusbonus.",
    cost: 42000,
    xp: 55,
    unlockLevel: 7,
    buildSeconds: 14,
    footprint: 1,
    maxSlope: 0.2,
    minElev: 1580,
    maxElev: 2600,
    color: "#3d8a8a",
  },
  {
    id: "piste-blue",
    category: "pistes",
    name: "Blaue Piste",
    blurb: "Leicht. Breite Abfahrt für Familien.",
    cost: 700,
    xp: 6,
    unlockLevel: 1,
    buildSeconds: 3,
    footprint: 1,
    maxSlope: 0.42,
    minElev: 1600,
    maxElev: 3200,
    color: "#2b7de9",
  },
  {
    id: "piste-red",
    category: "pistes",
    name: "Rote Piste",
    blurb: "Mittel. Mehr Tempo, mehr Nervenkitzel.",
    cost: 1100,
    xp: 9,
    unlockLevel: 2,
    buildSeconds: 3,
    footprint: 1,
    maxSlope: 0.7,
    minElev: 1700,
    maxElev: 3600,
    color: "#d64545",
  },
  {
    id: "piste-black",
    category: "pistes",
    name: "Schwarze Piste",
    blurb: "Schwer. Steil, Prestige, Experten.",
    cost: 1700,
    xp: 14,
    unlockLevel: 4,
    buildSeconds: 4,
    footprint: 1,
    maxSlope: 1.15,
    minElev: 1900,
    maxElev: 4000,
    color: "#1c1c1c",
  },
  {
    id: "snowpark",
    category: "pistes",
    name: "Snowpark",
    blurb: "Kicker & Rails. Zieht junge Gäste an.",
    cost: 22000,
    xp: 34,
    unlockLevel: 5,
    buildSeconds: 10,
    footprint: 1,
    maxSlope: 0.38,
    minElev: 1800,
    maxElev: 3000,
    color: "#f0c14a",
  },
  {
    id: "road",
    category: "pistes",
    name: "Zufahrt",
    blurb: "Strasse zum Tal. Nötig für Hotels & Parken.",
    cost: 400,
    xp: 3,
    unlockLevel: 1,
    buildSeconds: 2,
    footprint: 1,
    maxSlope: 0.28,
    minElev: 1560,
    maxElev: 2000,
    color: "#5a6570",
  },
  {
    id: "tree",
    category: "deco",
    name: "Arve",
    blurb: "Schöner Wald. Kleiner Zufriedenheitsbonus.",
    cost: 180,
    xp: 1,
    unlockLevel: 1,
    buildSeconds: 1,
    footprint: 1,
    maxSlope: 0.5,
    minElev: 1600,
    maxElev: 2500,
    color: "#1f3d2a",
  },
  {
    id: "rock",
    category: "deco",
    name: "Fels",
    blurb: "Natürliche Kulisse.",
    cost: 120,
    xp: 1,
    unlockLevel: 1,
    buildSeconds: 1,
    footprint: 1,
    maxSlope: 1.4,
    minElev: 1700,
    maxElev: 4300,
    color: "#6b6864",
  },
  {
    id: "viewpoint",
    category: "deco",
    name: "Aussichtspunkt",
    blurb: "Fotospot. Gäste lieben Gipfelblicke.",
    cost: 3500,
    xp: 10,
    unlockLevel: 3,
    buildSeconds: 5,
    footprint: 1,
    maxSlope: 0.35,
    minElev: 2200,
    maxElev: 3900,
    color: "#4aa3c7",
  },
  {
    id: "lights",
    category: "deco",
    name: "Flutlicht",
    blurb: "Nachtpisten. Verlängert den Betriebstag.",
    cost: 9000,
    xp: 16,
    unlockLevel: 5,
    buildSeconds: 6,
    footprint: 1,
    maxSlope: 0.5,
    minElev: 1700,
    maxElev: 3200,
    color: "#f4e27a",
  },
  {
    id: "snowmaker",
    category: "services",
    name: "Beschneiung",
    blurb: "Hält die Schneequalität hoch.",
    cost: 20000,
    xp: 32,
    unlockLevel: 3,
    buildSeconds: 8,
    footprint: 1,
    maxSlope: 0.5,
    minElev: 1700,
    maxElev: 3200,
    color: "#7ec8ff",
  },
  {
    id: "groomer",
    category: "services",
    name: "Pistenraupe",
    blurb: "Depot. Gepflegte Pisten, weniger Stau.",
    cost: 14000,
    xp: 22,
    unlockLevel: 2,
    buildSeconds: 8,
    footprint: 1,
    maxSlope: 0.3,
    minElev: 1580,
    maxElev: 2400,
    color: "#d9890f",
  },
  {
    id: "workshop",
    category: "services",
    name: "Werkstatt",
    blurb: "Senkt Unterhalt der Bahnen.",
    cost: 11000,
    xp: 18,
    unlockLevel: 3,
    buildSeconds: 8,
    footprint: 1,
    maxSlope: 0.28,
    minElev: 1580,
    maxElev: 2200,
    color: "#6d6d6d",
  },
  {
    id: "parking",
    category: "services",
    name: "Parkhaus",
    blurb: "Tagesgäste brauchen Parkplätze.",
    cost: 8000,
    xp: 14,
    unlockLevel: 1,
    buildSeconds: 6,
    footprint: 1,
    maxSlope: 0.18,
    minElev: 1560,
    maxElev: 1850,
    color: "#4a5560",
  },
  {
    id: "clinic",
    category: "services",
    name: "Bergrettung",
    blurb: "Sicherheit. Bonus auf schwarze Pisten.",
    cost: 17000,
    xp: 26,
    unlockLevel: 4,
    buildSeconds: 9,
    footprint: 1,
    maxSlope: 0.32,
    minElev: 1600,
    maxElev: 3000,
    color: "#d23b3b",
  },
  {
    id: "bus",
    category: "services",
    name: "Busbahnhof",
    blurb: "ÖV-Anschluss. Weniger Verkehrsstau.",
    cost: 12500,
    xp: 20,
    unlockLevel: 2,
    buildSeconds: 8,
    footprint: 1,
    maxSlope: 0.2,
    minElev: 1560,
    maxElev: 1850,
    color: "#1f7a4d",
  },
];

export const BY_ID: Record<ItemId, CatalogItem> = Object.fromEntries(
  CATALOG.map((c) => [c.id, c]),
) as Record<ItemId, CatalogItem>;

export const CATEGORIES: { id: Category; label: string; hint: string }[] = [
  { id: "lifts", label: "Bergbahnen", hint: "Seilbahnen & Lifte" },
  { id: "buildings", label: "Gebäude", hint: "Hotels, Shops & mehr" },
  { id: "pistes", label: "Pisten & Wege", hint: "Pisten, Routen & Strassen" },
  { id: "deco", label: "Dekoration", hint: "Bäume, Felsen & Objekte" },
  { id: "services", label: "Dienste", hint: "Werkstätten, Parken & Co." },
];

export const QUICK: ItemId[] = ["chair", "gondola", "tbar", "restaurant", "groomer", "viewpoint"];

export const LIFT_IDS: ItemId[] = ["tbar", "chair", "gondola", "tram"];
export const PISTE_IDS: ItemId[] = ["piste-blue", "piste-red", "piste-black", "snowpark", "road"];

export function isLift(id: ItemId) {
  return LIFT_IDS.includes(id);
}
export function isPiste(id: ItemId) {
  return PISTE_IDS.includes(id);
}

export const UPGRADES: UpgradeDef[] = [
  { key: "speed", label: "Geschwindigkeit", max: 3, cost: [1500, 4200, 9000] },
  { key: "cabins", label: "Kabinen", max: 3, cost: [2200, 5600, 12000] },
  { key: "capacity", label: "Kapazität", max: 3, cost: [1800, 5000, 11000] },
];

export function xpForLevel(level: number) {
  if (level <= 1) return 0;
  return Math.round(90 * Math.pow(level - 1, 1.65));
}

export function levelFromXp(xp: number) {
  let lvl = 1;
  while (xp >= xpForLevel(lvl + 1) && lvl < 40) lvl += 1;
  return lvl;
}

export function liftThroughput(item: CatalogItem, upgrades: { speed: number; cabins: number; capacity: number }) {
  const base = item.capacity ?? 400;
  return Math.round(base * (1 + upgrades.capacity * 0.18 + upgrades.cabins * 0.12 + upgrades.speed * 0.08));
}
